name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PRODUCTS_CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vQyKHkHlToliTiCgMJNa-5iE-eW-PVeD127sY6y6UOH5kIr4A_ah2IzlAOt2dC0tn-VduVoJVKcgcWo/pub?gid=0&single=true&output=csv
  FIELDS_CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vQyKHkHlToliTiCgMJNa-5iE-eW-PVeD127sY6y6UOH5kIr4A_ah2IzlAOt2dC0tn-VduVoJVKcgcWo/pub?gid=1947094682&single=true&output=csv
  REVALIDATE_SECRET: secret

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
    - run: npm run dev & npx wait-on http://localhost:3000
    - run: npm run integration
