name: Node.js CI

on:
  push:
    branches: [ main, stream ]
  pull_request:
    branches: [ main, stream ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
    - run: npm run dev & npx wait-on http://localhost:3000
    - run: npm run integration
